### ISSUE TITLE
[question] Is there a way to load vendor/autoload.php?

### ISSUE THREAD

**Issue by antonioribeiro** [BenConstable/phpspec-laravel#46]
My use case is: I develop (Laravel) packages inside the vendor dir of an application. It's better to test the package, at leas for me, but I know it may sounds odd. That being said:

Loading the app.php is not enough since some classes are only autoloadable if you load the application's vendor/autoload.php.

So, after some tries, it worked for me loading it inside `createApplication()`:

    protected function createApplication()
    {
        require dirname($this->appPath).'/../vendor/autoload.php';

        ...
    }
 
Then, my next step was to extend LaravelObjectBehavior and Laravel, but I got:

`Declaration of spec\PragmaRX\Google2FALaravel\LaravelObjectBehavior::setLaravel(spec\PragmaRX\Google2FALaravel\Laravel $laravel) must be compatible with PhpSpec\Laravel\LaravelBehaviorInterface::setLaravel(PhpSpec\Laravel\Util\Laravel $laravel) in /Users/antoniocarlos/code/pragmarx/pragmarx.com/vendor/pragmarx/google2fa-laravel/tests/spec/LaravelObjectBehavior.php on line 7`

Because, of course, the class I'm creating is not the class you used in the interface type hint, which should not use type hints, or at least also use interfaces in type hints.

So, asking it again: is there a way to autoload it via your extension?

Thank you, also for the work you put on this extension.

**Comment by antonioribeiro** [comment]
Some screenshots to show more

With and without it autoloading:

![image](https://user-images.githubusercontent.com/3182864/27310776-0d3d0f30-5533-11e7-92f8-923b63c491e2.png)

![image](https://user-images.githubusercontent.com/3182864/27310814-49413da8-5533-11e7-9da0-1a8d0b9bda31.png)

![image](https://user-images.githubusercontent.com/3182864/27310823-57d52e56-5533-11e7-970b-eefb0983292f.png)

**Comment by antonioribeiro** [comment]
To fix it, I added this to my bootstrap/app.php

```
if (getenv('APP_ENV') === 'testing') {
    require __DIR__.'/../bootstrap/autoload.php';
}
```

But this is not not an ideal solution.

**Comment by BenConstable** [comment]
Hi,

Unfortunately this package isn't intended for your use case (i.e package development). It's targeted at users writing tests for a full Laravel installation.

I'm not sure of the package you're building, but you should just be able to use Phpspec without this extension to write your tests. It's recommended in the Laravel docs (see ["A note on facades"](https://laravel.com/docs/5.4/packages)) that you use contracts rather than facades when developing packages, which will mean you don't have any need to access the IoC container in your tests.

Hope that helps.
